git add -f ./lab8/Lab_8.ipynb
git add -f ./lab8/01-lab_8.ipynb
git add -f ./lab1/01-lab1.ipynb
git add -f ./lab6/lab6.ipynb
git add -f ./lab7/01-lab7.ipynb
git add -f ./lab7/Lab_7.ipynb
git add -f ./lab9/fftnotebook.ipynb
git add -f ./lab9/fft_2d.ipynb
git add -f ./lab9/xcorr_fft.ipynb
git add -f ./lab10/Lab_10.ipynb
git add -f ./lab10/01-lab_10.ipynb
git add -f ./lab5/01-lab5.ipynb
git add -f ./lab2/01-lab2.ipynb
git add -f ./lab3/01-lab3.ipynb
git add -f ./lab4/01-lab4.ipynb
git add -f ./demonstrations/dask_zarr_demo.ipynb
git add -f ./demonstrations/numba_demo.ipynb
git add -f ./demonstrations/scipy_integrate/solve_ivp_example.ipynb
git add -f ./demonstrations/scipy_integrate/scipy_lab4.ipynb
git add -f ./demonstrations/joblib_parallel/joblib_example.ipynb
git add -f ./demonstrations/pandas.ipynb
